// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crawwjxenrziwdbzxwre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyYXd3anhlbnJ6aXdkYnp4d3JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1MzUyOTcsImV4cCI6MjA1MDExMTI5N30.CskJCbqWWWM9_i7eGoWkHMxMgcPIkOq35RgA4a3NBpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);